extends: default

page:
    layout: portrait 
    margin: [0.75in, 0.5in, 0.75in, 0.5in]
    size: A4

font:
  catalog:
    CoverFont:
        normal: got-heroin.regular.ttf
    BaseFont:
        # normal:      underwood-champion.regular.ttf
        # normal:      kingthings-trypewriter-2.regular.ttf
        normal:       underwood-champion.regular.ttf
        italic:       underwood-champion.regular.ttf
        bold:         underwood-champion.regular.ttf
        bold_italic:  underwood-champion.regular.ttf
    HeaderFont:
        normal:   if.regular.ttf
        bold:     if.regular.ttf
    Header2Font:
        normal: got-heroin.regular.ttf
        bold:   got-heroin.regular.ttf
    CodeFont:
        normal: dotty.regular.ttf
    FooterFont:
        normal:      dotty.regular.ttf
    SidebarHeaderFont:
        normal: got-heroin.regular.ttf
        bold:   got-heroin.regular.ttf
    SidebarFont:
        normal:      tippa.regular.ttf 
        italic:      tippa.regular.ttf 
        bold:        tippa.regular.ttf 
        bold_italic: tippa.regular.ttf 

title-page:
  background-color: #EAEAEA
  font:
      color: #56a6a0
      family: HeaderFont
      size: 30
  title:
    font:
        color: #56a6a0
        family: CoverFont
        size: 70
  authors:
    font:
        color: #56a6a0
        family: CoverFont
        size: 30
  subtitle:
    font:
        color: #56a6a0
        size: 28


base:
    font:
        color: #222222
        family: BaseFont
        size: 14
    align: justify

heading:
    h1:
        align: center
        font:
            color: #4a6db2
            family: HeaderFont
            size: 30
        text_transform: uppercase
        margin_top: 50

    h2:
        align: center
        font:
            color: #4a6db2
            family: HeaderFont
            size: 24
        text_transform: uppercase
    h3:
        align: left 
        font:
            # color: #d78d42
            color: #70819d
            family: Header2Font
            size: 30
        text_transform: uppercase
    h4:
        align: left 
        font:
            color: #70819d
            family: Header2Font
            size: 20
        text_transform: uppercase

code:
    font:
        family: CodeFont
        size: 24
        color:  #606060
    # background_color: #e4e4d8
    # background_color: #f0dfbd
    background_color: #ffffff
    border_width:     1
    border-color:     #b0b0b0

sidebar:
    font:
        family: SidebarFont
        size:   12
        style:  normal
    background_color: #f3f3f0
    border_width: 1
    border-color: #2f8e6d
sidebar_title:
    font:
        family: SidebarHeaderFont
        size:   30
        style:  normal
        color:  #2f8e6d
    text_transform: uppercase

#header:
#    height: 0.5in
#    line_height: 1.5
#    recto_content:
#        left: '*{page-number}* | {document-title}'
#    verso_content:
#        right: '{chapter-title} | *{page-nymber}*'
 
footer:
    height: 0.5in
    line_height: 0.5
      #recto_content:
      #  left: ' *{page-number}* | {document-title} '
      #verso_content:
      #  right: ' {chapter-title} | *{page-number}* '
    padding: [10, 0, 0, 0]
    font:
        family: FooterFont
        size: 28
        style: normal
        color: #909095

