extends: default

page:
    layout: portrait 
    margin: [ 0.75in, 0.5in, 0.75in, 0.5in ]
    margin-inner: 1.25in
    margin-outer: 0.75in
    size:   A4

ulist:
    marker:
      disc:
          content: "*"    # Default bullet (•)
      square:
          content: "\u25AA"    # Square bullet (▪)
      circle:
          content: "\u25E6"    # Circle bullet (◦)

font:
  catalog:
    CoverFont:
        normal: got-heroin.regular.ttf
    BaseFont:
        normal:       underwood-champion.regular.ttf
        italic:       underwood-champion.regular.ttf
        bold:         underwood-champion.regular.ttf
        bold_italic:  underwood-champion.regular.ttf
        # normal:      kingthings-trypewriter-2.regular.ttf
        # bold:        kingthings-trypewriter-2.regular.ttf
        # italic:      kingthings-trypewriter-2.regular.ttf
        # bold_italic: kingthings-trypewriter-2.regular.ttf
    HeaderFont:
        normal:   if.regular.ttf
        bold:     if.regular.ttf
    Header2Font:
        normal:   if.regular.ttf
        bold:     if.regular.ttf
    CodeFont:
        # normal:   dotty.regular.ttf
        # normal:   dotrice.regular.ttf
        normal:   hydrogentype.regular.ttf
    FooterFont:
        normal:   dotty.regular.ttf

    SidebarHeaderFont:
        normal:   got-heroin.regular.ttf
        bold:     got-heroin.regular.ttf
    SidebarFont:
        normal:       underwood-champion.regular.ttf
        italic:       underwood-champion.regular.ttf
        bold:         underwood-champion.regular.ttf
        bold_italic:  underwood-champion.regular.ttf
        # normal:      kingthings-trypewriter-2.regular.ttf
        # bold:        kingthings-trypewriter-2.regular.ttf
        # italic:      kingthings-trypewriter-2.regular.ttf
        # bold_italic: kingthings-trypewriter-2.regular.ttf
        # normal:      tippa.regular.ttf 
        # italic:      tippa.regular.ttf 
        # bold:        tippa.regular.ttf 
        # bold_italic: tippa.regular.ttf 

title-page:
  background-color: #EAEAEA
  font:
      color:  #56a6a0
      family: CodeFont
      size:   20
  title:
    font:
        color: #56a6a0
        family: CoverFont
        size: 70
  authors:
    font:
        color:  #56a6a0
        family: CoverFont
        size:   36
  subtitle:
    font:
        color: #56a6a0
        size: 20


base:
    font:
        color:  #222222
        family: BaseFont
        size:   14
    align: justify

heading:
    h1:
        align: center
        font:
            # color: #4a6db2
            color: #56a6a0
            family: HeaderFont
            size: 30
        text_transform: uppercase
        margin_top: 50

    h2:
        align: center
        font:
            # color: #4a6db2
            color: #56a6a0
            family: HeaderFont
            size: 24
        text_transform: uppercase
    h3:
        align: left 
        font:
            # color: #d78d42
            # color: #70819d
            color: #56a6a0
            family: Header2Font
            size: 20
        text_transform: uppercase
    h4:
        align: left 
        font:
            # color: #70819d
            color: #56a6a0
            family: Header2Font
            size: 20
        text_transform: uppercase

code:
    font:
        family: CodeFont
        size:   17
        color:  #808492
        # color:  #808492
    # background_color: #e4e4d8
    # background_color: #f0dfbd
    background_color: #ffffff
    border_width:     1
    border-color:     #b0b0b0

codespan:
    font:
        family: CodeFont
        size:   17
        color:  #808492

sidebar:
    font:
        family: SidebarFont
        size:   14
        style:  normal
        # color:  #4a6db2
        color: #70819d
    emphasis_strong:
        font-style: bold
        font-color: #FF0000
    background_color: #f3f3f0
    border_width:     1
    border-color:     #70819d

sidebar_title:
    font:
        family: SidebarHeaderFont
        size:   30
        style:  normal
        # color:  #4a6db2
        color: #70819d
    text_transform: uppercase

#header:
#    height: 0.5in
#    line_height: 1.5
#    recto_content:
#        left: '*{page-number}* | {document-title}'
#    verso_content:
#        right: '{chapter-title} | *{page-nymber}*'
 
footer:
    height: 0.5in
    line_height: 0.5
      #recto_content:
      #  left: ' *{page-number}* | {document-title} '
      #verso_content:
      #  right: ' {chapter-title} | *{page-number}* '
    padding: [10, 0, 0, 0]
    font:
        family: FooterFont
        size: 28
        style: normal
        color: #909095

role:
  strong-red:
    font-color: #d64502
  strong-blue:
    font-color: #0680d1

