from:    HQ
subject: Game Over!
-----------------------------
We regret to inform you that our mission has been canceled.

There is no budget left to continue, and the administration has requested to cease the operations.

It has been a wild ride:

The mission lasted for [$stat/day] days, we completed [$stat/experiments] experiments, and burned through $[$stat/burned] cash.

Now is the time to say goodbye to our faraway mechanical colleague. You've been a good friend! Now, fly away into the coldness of outer space!

Turn off all Angel-F5 onboard devices and telemetry and let it rest!