at:      2
from:    HQ
subject: Get Started
----------------------------

ANGEL-F5 is the latest in the series of our deep space probes.

The probe is controlled by the main computer - Command & Control Subsystem. You can see its memory snapshot in the Core Monitor panel.

Programs are executed from the address 0x0000 and up. You can change the content of any memory cell by clicking on it and selecting the desired code in the code list to the right.

Once the program is ready, upload it to the probe through our Deep Space Network by pressing the "Upload" button. The probe will start to execute the program immediately upon receiving the last byte.

For security reasons, we will unlock only a single instruction. But more will be unlocked once you get yourself familiar with the probe's internal systems.

Good luck!
