at: 1.8
from:    HQ
subject: Get Started
----------------------------

There will be very long lines here to test it out.
Formatter should split and format the lines
relative to the screen size and considering
some ```preformatted strings``` and other
things like [the links].
Maybe **bold** as well...


 ============
 How to Start
 ============

 * Learn Assembly
 * Learn Machine Language
 * Learn Orbital Mechanics


 Assembly
 --------

some examples over here:

 ```
 mov 
 add
 push
 over
 1F
 ```

