at:      2
from:    Tech Sup
subject: Get Started
----------------------------

**ANGEL-F5** is the latest in our series of deep-space probes.

A spaceframe controls the probe - its central and most powerful computer.
**ANGEL-F5 spaceframe** is built on **DUSTY-12 architecture**, which defines its core characteristics and the list of available commands.

Core Monitor shows instructions defined by the firmware. You can modify these instructions to change the probe behavior.

Programs are executed from the address 0x0000 and up. You can change the content of any memory cell by clicking on it and selecting the desired code in the code list to the right.

These codes are split into two major categories: number instructions that push values onto the data stack and commands to perform various actions (often using numbers previously pushed onto the stack as input parameters).

You can select the desired way to execute the program by pressing the Step/Walk/Run button. Once pressed, the firmware will be uploaded over our **Deep Space Network**, flushed, and executed on the probe.

For security reasons, we will unlock only a single instruction. But more will be unlocked once you get familiar with the probe's internal systems.

Good luck!

