at: 1.6
from:    HQ
subject: Got a problem!
----------------------------
We have a problem.

The specs for the **Angel-F5** probe were designed in metric units, but the RTG manufacturer interpreted them as imperial. As a result, the probe doesn't have enough power to function properly.

Now the probe firmware MUST be debugged and reprogrammed remotely in native assembly.

Oh, the horror!

And our star developers... They were React developers... They are no longer with us...

Their job expectation was to lay out beautiful pictures of gas giants on the mission website - not remotely fix the machine code for the failing probe!
One of them told us to (quote) "debug this hexadecimal deep space horror yourself" and took a sabbatical. Another one immediately quit and downshifted as far from the space program as possible. Now he grows potatoes on a farm.

Now we don't have anyone willing or capable to save the probe, but you.

You are the only hope of this space program! And who knows... Maybe of all humanity!
