from:    Tech Sup
subject: Telemetry
----------------------------

ANGEL-F5 engineering telemetry is controlled by the data lines.
Each line is responsible for a particular on-board device or instrument.
You can use the ODAT command to open a particular data line.

Data line manifest:

 0. Gyroscope
 1. RTGs
 2. Battery
 3. Command & Control System
 4. Antenna
 5. Tape Recorder
 6. Wide-Angle Camera
 7. Stack Inspector

