at:      1.1
from:    HQ
subject: Welcome!
----------------------------
Welcome to the Deep Space Exploration Program!

On your first day, we enabled the access
to our email system.

Our department is responsible for the probe
designated ANGEL-F5, which is one of the latest
exploration vehicles at the edge
of our solar system.

The probe specifications will be emailed
to you shortly. They contain technical details
on onboard instrumentation and programming
hints for the Control and Data Subsystem.
We expect you to familiarize yourself with
the specs.

Meanwhile, we have already connected your Core Monitor to the uplink interface
of our Deep Space Network.
So you can already update the probe's software.

We realize that you just started and don't have any experience in remote deep-space debugging.
But what can go wrong?
